version: '3.7'

services:
  currency-exchange:
    image: sephyron/currency-exchange:1.1
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
 
networks:
  currency-network: